# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Mihir Walia
title: Cybersecurity Enthusiast | Penetration Tester 
email: mihirswalia@gmail.com
# email_title: Email (Email title override)
#phone: +91 7219533255
# phone_title: Phone (Phone title override)
#website: https://mihirswalia.github.io/Terminal-CV/
#website_title: Terminal CV

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: jekyllrb
github_username:  MihirSWalia
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyl
instagram_username: _shade.z_
linkedin_username: mihir-walia-972642173
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
#orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: Medium
#  icon: https://fontawesome.com/icons?d=gallery&s=brands&m=free
#  url: https://shad3z.medium.com/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: <strong>About Me</strong> 
about_profile_image: dp.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a cybersecurity and automotive enthusiast. I love and enjoy testing the security of different systems. Being curious about things and finding a way to break into the system is a thrill of its own which I enjoy the most. Always been keen on learning and gaining more knowledge and sharing it with my fellow learners. I am a dedicated person who wishes to explore more in the field of Cyber Security and make a like of it. Other than cybersecurity i also enjoy:
    - Bike rides,
    - Table Tennis,
    - Sketching,
    - Photography,
    - Competetive gaming,
    - <a href="https://shad3z.medium.com">Bloging</a>.
content:
  - title: <strong>Education</strong>
    layout: list
    content:
      - layout: left
        title: New York Institue of Technology
        sub_title: MS in Cybersecurity
        caption: 2021 - Present
        quote: >
          New York Tech is emerging from recent challenges as a stronger, more future-focused university. As a dynamic, highly ranked, and accredited not-for-profit university, we're committed to educating the next generation of leaders, inspiring innovation, and advancing entrepreneurship.
        description: | # this will include new lines to allow paragraphs
          We design, implement, and maintain software tools to support network security across multiple operating systems, overseeing the information lifecycle of an organization from planning and acquisition to implementation. We also study algorithm concepts, computer forensics, risk management and legal issues, and intrusion detection and hacker exploits.
      
      - layout: left
        title: Ajeenkya D.Y. Patil University
        sub_title: BCA in Cloud Technology and Information Security 
        caption: 2017 - 2020
        quote: >
          ADYPU was awarded for being the best private university in 2018 under Educational Excellence Awards. In 2019, ADYPU was awarded as the best private university by The Associated Chambers of Commerce and Industry of India (ASSOCHAM) and recognised as the ‘Best Innovation in Education’.
        description: | # this will include new lines to allow paragraphs
          Completed this course with 9.05/10 CGPA. This unique course provides dual career options for the students in the fast growing technology sectors of Cloud Technology and Information Security. In addition to all the mandatory subjects of a traditional BCA, this specialized course offers in-depth practical know-how of the current trends.
  - title: <strong>Experience</strong>
    layout: list
    content:
      - layout: left
        title: SecOnset Community
        sub_title: Core Team Member
        caption: December 2020 - Present
        #link: Link to company (optional)
        quote: >
          SecOnset is the easiest platform to build your career in cybersecurity. We believe in technology and Open internet to scale your dream with basic to advance level.
        description: | # this will include new lines to allow paragraphs
          Being a core member of an upcoming community, my work include writing blogs on <mark><a href="https://shad3z.medium.com/">Medium</a></mark> such as Capture the Flag write-ups, explaining concepts and any cyber security related content which helps begginers to grow. Other than that we discuss and plan future online events or seminars.
      - layout: left
        title: Testbook Edu Solutions
        sub_title: DevOps Intern
        caption: January 2020 - April 2020
        link: https://testbook.com
        quote: >
          Testbook is a company that provides online courses and test series for various fields such as Banking, SSC, Railways, Engineering, Teaching, Defence, Civil Services and State Exams   
        description: | # this will include new lines to allow paragraphs
          As an Devops intern I had to install and configure various tools on <mark>GCP</mark> and <mark>AWS</mark> instances, Grant and Revoke <mark>No-SQL</mark> database access for each project, Setup and manage monitoring environment for all the instances and tools and wrtie many <mark>Shell Scripts</mark> for automating tasks.
      - layout: left
        title: Testbook Edu Solutions
        sub_title: Quality Assurance Intern
        caption: May 2018 - August 2018
        link: https://testbook.com
        description: | # this will include new lines to allow paragraphs
          My role was to performed <mark>manual testing</mark> of the android application, frontend of the website and the universal backend api by writing test cases and executing them. I also represented the QA team for the official team meetings. My other job was to helped the support team with all the technical issues with customers. I also managed a case of bug bounty with the server having RCEs and helped the Bug hunter communicate with the team.

  - title: <strong>Skills</strong>
    layout: list
    content: 
      - layout: left
        title: Languages
        description: | #
          Bash, Python, HTML5, CSS, Bootstrap, Js, C, C++ and Ruby.
      - layout: left
        title: Grip on
        description: | #
          Ethical Hacking, Penetration Testing, Information Security, Server Operating System, Cryptography, Networking, Scripting, Cloud Computing, Google Cloud Platform, Amazon Web Services, Programming, Database Management and Digital Forensics.
      - layout: left
        title: Tools
        description: | #
          Metasploit, Nmap, Burp-Suite, Go-Buster, Dirsearch, Enum4linux, Hydra, Sqlmap, Nessus, Google Dorking, Shodan, Wireshark, Aircrack-ng, John the ripper, Nikto, Owasp-Zap, Cupp, Samba, Apache, MongoDB, MySQL, Nginx, Nagios, Graylog, Jenkins, Redis, FTK imager, Recuva, Icare Pro, Git, GCP, AWS, Digital Ocean, Docker and Supervisor. 


  - title: <strong>Projects</strong> # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: WiFi Jammer
        description: | # this will include new lines to allow paragraphs
          This project was done using a Node MCU chip which was programmed to deauth devices connected to a router and host multiple fake access points using python code.

      - layout: left
        title: Keylogger
        description: | # this will include new lines to allow paragraphs
          Scripts to run in the background when run and capture keyboard activity and save it to a hidden file. Different files for Windows OS and Linux OS.

      - layout: left
        title: Web Crawler
        description: | # this will include new lines to allow paragraphs
          Python tool which can list email address, sub-domains or a specific term from a web application's source code by scanning through it.
          
      - layout: left
        title: IDS / IPS
        description: | # this will include new lines to allow paragraphs
          Installing and configuring Suricata's Intrusion Detection System and Intrusion Prevention System on Debian OS and testing by attacking by another Parrot OS.

      - layout: left
        title: Jenkins
        description: | # this will include new lines to allow paragraphs
          This project included the tool Jenkins for automatiom. I created a JenkinsFile for automating Continuous Integration / Continuous Deployment for backend of production server at Testbook Edu Solutions.

      - layout: left
        title: Automating Backups
        description: | # this will include new lines to allow paragraphs
          Bash script using gcloud commands to locate the latest production server, then create and image of the instance and store it to a storage of different location.          

      - layout: left
        title: MongoDB
        description: | # this will include new lines to allow paragraphs
          Installed and configured MongoDB on a virtual network with a primary and several secondary replica sets.
          
      - layout: left
        title: Fee Management
        description: | # this will include new lines to allow paragraphs
          This application was written in Java and was configured with MySQL to manage ADYPU's fee records. It had a GUI and  alerts system for student who haven't paid the fee.

  - title: <strong>Publication</strong>
    layout: list
    content:
      - layout: left
        title: IJRECE Paper 
        description: |
          Mihir Walia, Sneha Ambore “<a href='http://www.i2or-ijrece.com/vol.-7-issue-2--csnsda-.html'>Methods of Managerial, Procedural and Technical Controls for Virus and Worms</a>”.
      
  - title: <strong>Certifications</strong>
    layout: list
    content:
      - layout: left
        title: ICSI
        description: | 
          Certified Network Security Specialist (CNSS).
      
      - layout: left
        title: IBM
        description: | 
          Cybersecurity Compliance Framework System Administration.
         
      - layout: left
        title: Passmarks
        description: |
          OSForensics Triage Certification.
      
      - layout: left
        title: IACET 
        description: |
          210W-06 ICS Cybersecurity Threats.
       
      - layout: left
        title: LinkedIn
        description: |
          Penetration Testing : Advanced Kali Linux, Penetration Testing : Advanced Web Testing, Ethical Hacking : The Complete Malware Analysis Process & Amazon Web Services for Architects Essential Training(2017).
      
      - layout: left
        title: Hewlett Packard Enterprise
        description: |
          Artificial Intelligence.
      
      - layout: left
        title: Udacity
        description: |
          Python Nanodegree.
         
      - layout: left
        title: VMware
        description: |
          Virtualization for Beginners.
          
  - title: <strong>Badges</strong>
    layout: list
    content: 
      - layout: left
        title: Rangeforce
        description: | 
          Blue Team Star Challenge & SOC Analyst 1.
        
      - layout: left
        title: PenetesterLab
        description: | 
          Essential Badge, Unix Badge, PCAP badge, White Badge & Serialize Badge.
        
      - layout: left
        title: TryHackMe
        description: |
          Burp'ed, Nessus Nerd, Cat Linux.txt, Metasploitable, ICE, Blue, Webbed, Linux PrivEsc, Windows PrivEsc, ohSINT, Mr.Robot, OWASP TOP 10, Christmas 2019, Overpassed & 7 Day Streak.
      
      - layout: left
        title: Qwik Labs
        description: | 
          Google Cloud Essentials.
  
  - title: <strong>A Little More About Me</strong>
    layout: list
    content: 
      - layout: left
        title: Social
        description: | #
           - Core team member of SecOnSet community,
           - Written several infosec and CTF based writeups on medium,
           - University's official event photographer, 
           - Volunteered in cleaning beaches, 
           - University's convocation volunteer, 
           - Volunteered in University's Cyber Cell, 
           - Donated books and clothes to orphanage,
           - Bike rides with groups(Member of Kawasaki Navi Mumbai).
      - layout: left
        title: Sports
        description: | #
           - 1st Runner-up in Boxing (55kg) in College event, 
           - 1st Runner-up in Table Tennis in College event, 
           - Hosted the Table Tennis matches for Annual event(Impetus).
      - layout: left
        title: Cultural Events
        description: | #
          - Comic Con 2018 Volunteer,
          - Participated in sketching competetions,
          - photography competitions.
# Footer
footer_show_references: true
references_title: <a href='https://mihirswalia.github.io/Terminal-CV/'>Terminal CV</a>

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
